apiVersion: apps/v1
kind: Deployment
metadata:
  name: vincewebapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vincewebapp
  template:
    metadata:
      labels:
        app: vincewebapp
    spec:
      containers:
      - name: vincewebapp
        image: 145988340565.dkr.ecr.us-west-2.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
